apiVersion: v1
kind: Service
metadata:
  name: kafkaproducerdeploymentservice
spec:
  selector:
    app.kubernetes.io/name: kafka-producer-deploymentpod
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80